sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t liaa2/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true liaa2/docker-react npm run test -- --coverage
