sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -e CI=true -t liaa2/docker-react -f Dockerfile.dev .

script:
  - docker run liaa2/docker-react npm run test -- --coverage
